### ISSUE TITLE
Custom card not showing / empty

### ISSUE THREAD

**Issue by SgtFoose** [timjong93/lovelace-wtw#3]
Hi Tim,

My card does show when I edit the UI but not when I finalize it? Any clue?

I used:
type: custom:wtw-card

Folder wtw-cards.js:
/config/www/lovelace-wtw/wtw-cards.js

Folder wtw.yaml:
/config/packages/wtw.yaml

configurations.yaml:
```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

#HACS
my:

#Logger
logger:

#WHR930 Mosibi
homeassistant:
  packages:
    wtw: !include packages/wtw.yaml

```
![Custom Card Error1](https://user-images.githubusercontent.com/17387175/212415307-9393800a-ad72-499f-acd3-ca355ebe65b0.png)
